FROM node:lts-bullseye-slim

# ENV NODE_ENV=production
ARG VITE_API_URL=http://192.168.0.100:3001

WORKDIR /usr/src/app

RUN yarn set version berry

# copy needed items only
COPY package.json .
COPY yarn.lock .yarnrc.yml ./
COPY .yarn ./.yarn
COPY packages/core ./packages/core
COPY packages/api ./packages/api

# run install and build
RUN yarn workspace @gamekeeper/web install
# for some reason i need to run install on core otherwise i get missing node_modules error
RUN yarn workspace @gamekeeper/core install

COPY apps/web ./apps/web

RUN yarn workspaces foreach -Rpt --from 'apps/web' run build

EXPOSE 3000

CMD ["yarn", "dlx", "serve", "apps/web/dist", "-p", "3000"]
