FROM node:lts-bullseye-slim

# ENV NODE_ENV=production
ENV PORT=3000
ENV DB_PATH=test

WORKDIR /usr/src/app

RUN yarn set version berry

# copy needed items only
COPY package.json .
COPY yarn.lock .yarnrc.yml ./
COPY .yarn ./.yarn
COPY packages/core ./packages/core
COPY packages/db ./packages/db
COPY apps/api ./apps/api

RUN yarn workspace @gamekeeper/api install
RUN yarn workspaces foreach -Rpt --from 'apps/api' run build

EXPOSE 3000

CMD ["yarn", "workspace", "@gamekeeper/api", "start"]
