name: Build and Run Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - turbo

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: build docker image
        run: docker build -t local/gamekeeper-web Dockerfile.web

